### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by danshapir** [apprentus/atom-ember-cli-helper#17]
Hey,

Unless I'm missing something, no matter what I've tried, I keep getting "is not recognized as an internal or external command" error when I try to run the "Server" or "Test" or any other function. 
I tried any path I could think of and none worked.

Can you please describe the default configuration for Windows?

Thanks,
Dan

**Comment by alexlafroscia** [comment]
Honestly, I've got not idea. I did the development on OSX, and it tries to find the `ember` executable in the default OSX location for them.  If I were you, I'd try overriding the path to the `ember` executable in the addon's settings.

**Comment by danshapir** [comment]
Hey, 

That's what I did, but nothing worked. It never found the executable.

**Comment by zaccharles** [comment]
@danshapir Open up a new command prompt and run `where ember` and `where node`. Copy those two values into `Path to Ember Executable` and `Path to Node Executable` in the Ember Cli Helper settings.

Also make you should make sure you have ember installed globally using `npm install -g ember`.

After doing the above, I could use _Server_ and _Test_ on Windows from Atom, but not _Generate_.

**Comment by zaccharles** [comment]
Just an update, I just updated Atom and now everything (including Generate) is working.

**Comment by zaccharles** [comment]
Here are my settings in case it helps:

![image](https://cloud.githubusercontent.com/assets/5722738/12765858/468dcf92-ca09-11e5-95e4-bf32a11501ce.png)
