### ISSUE TITLE
generators are not showing 

### ISSUE THREAD

**Issue by johncodesigns** [apprentus/atom-ember-cli-helper#19]
the generator types like route controller etc not showing

**Comment by zaccharles** [comment]
Which OS are you using @johncodesigns? I'm guessing Windows?

**Comment by BryanHunt** [comment]
I just started having the same problem on OS X.  Here is the error from the console:

Error: There was a problem reading the generator options(…)
/Users/bhunt/.atom/packages/ember-cli-helper/lib/generator-list-view.coffee:95 Uncaught (in promise)

**Comment by mariusandra** [comment]
@johncodesigns this probably means that `ember-cli-helper` was not able to find your ember project. I have added a visible error message for these cases.

@BryanHunt do you still get the error with v0.9.4?

**Comment by mariusandra** [comment]
I did a few more changes (more verbose errors) and pushed out v0.9.6. 

Closing for now and will reopen if more issues are found.
