### ISSUE TITLE
error finding ember executable

### ISSUE THREAD

**Issue by joedaniels29** [apprentus/atom-ember-cli-helper#21]
interesting error:
```
Failed to spawn command /usr/local/bin/ember. Make sure /usr/local/bin/ember is installed and on your PATH
```
Ember is intact at `/usr/local/bin` so I wonder if anyone knows whats up.

**Comment by joedaniels29** [comment]
Since its asking whether Ember is in my path, well, I use zsh, and zsh has usr/local/bin in it's path. Am i missing something for atom to pick it up?

**Comment by etuchscherer** [comment]
Same problem here, I've got zsh && I had the same error. An easy workaround was to symlink ember to /usr/local/bin.

    ln -s $(which ember) /usr/local/bin/ember
