### ISSUE TITLE
nodemon not working with cofee for starting the server 

### ISSUE THREAD

**Issue by johncodesigns** [apprentus/atom-ember-cli-helper#22]
![ice_screenshot_20151108-021518](https://cloud.githubusercontent.com/assets/9107477/11017216/a68aac60-85be-11e5-803b-bf835927cfe2.png)
in the ./bin/www as my start option in the package.json file

**Comment by mariusandra** [comment]
Hey, not sure how this is connected to the atom-ember-cli-helper...?
