### ISSUE TITLE
Customize Ember Location

### ISSUE THREAD

**Issue by vratnagiri-veriskhealth** [apprentus/atom-ember-cli-helper#23]
I'm using nvm and so, ember and node aren't available at the default paths. It would be nice to be able to customize those locations, but I couldn't find a 'settings' on this plugin.

**Comment by zaccharles** [comment]
This can already be done.

1. Open Atom and press `Ctrl+Comma` to open Settings.
2. Go to Packages and type `ember-cli-helper` in the search box.
3. Click the `Settings` button.
4. Scroll down if necessary, and you'll see the settings you're after.

![image](https://cloud.githubusercontent.com/assets/5722738/12763748/c77ab29c-c9fe-11e5-92a5-136c5abf207c.png)

![image](https://cloud.githubusercontent.com/assets/5722738/12763763/e3cf60f0-c9fe-11e5-87c0-2bb3b79646b8.png)

**Comment by vratnagiri-veriskhealth** [comment]
It's wierd, I don't see the settings button for this package. I do see it for all my other packages:

Here's the search page:
[X]

Here's when I click into the search resutl page:
[X]

________________________________

**Comment by vratnagiri-veriskhealth** [comment]
Looks like the images were stripped from my email reply.

![image](https://cloud.githubusercontent.com/assets/6776772/12765453/fc18614a-c9bb-11e5-8487-5ac0f35fdd3c.png)

![image](https://cloud.githubusercontent.com/assets/6776772/12765469/13a21a7c-c9bc-11e5-8f8b-7f531ac48828.png)

**Comment by vratnagiri-veriskhealth** [comment]
Oh, sorry, I just noticed after I posted the screenshots that the plugin was disabled. I enabled it and after restarting atom, the settings button appeared.

Sorry for the false alarm. Thanks for your prompt reply!

**Comment by zaccharles** [comment]
:+1:

**Comment by robbyoconnor** [comment]
Should probably close this.
