### ISSUE TITLE
Component/Template shortcut (ctrl+alt+e) only searches active pane

### ISSUE THREAD

**Issue by XaserAcheron** [apprentus/atom-ember-cli-helper#24]
When using the ctrl+alt+e shortcut (and presumably `ctrl+alt+r` as well -- can't test since I don't use controllers), only the active pane is searched for the corresponding component/template. If it's already open in a tab in a different (non-active) pane, it reopens the file in a new tab in  the active pane rather than switching to the existing tab.

Should be fixable by adding the `searchAllPanes` option to the `atom.workspace.open` call in `openBestMatch`.

**Comment by mariusandra** [comment]
I guess this can be closed then :)
